services:
  #frontend:
  #  image: lab/frontend
  #  build:
  #    context: ./frontend
  #    dockerfile: Dockerfile
  #  ports:
  #    - "5173:5173"
  #  depends_on:
  #    - backend-loadbalancer
  
  loadbalancer:
    image: nginx:1.27.4-alpine3.21
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "3000:3000"
    depends_on:
      - backend1
      - backend2
      - backend3
  
  backend1:
    image: lab/backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - PORT=3001
    ports:
      - "3001:3001"
  
  backend2:
    image: lab/backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - PORT=3002
  
  backend3:
    image: lab/backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - PORT=3003
