services:
  frontend:
   image: lab/frontend
   build:
     context: ./frontend
     dockerfile: Dockerfile
   environment:
     - PORT=3000
   ports:
     - "8080:5000"
   depends_on:
     - loadbalancer

  loadbalancer:
    image: nginx:1.27.4-alpine3.21
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "3000:3000"
    depends_on:
      - backend1
      - backend2
      - backend3
      - backend4
      - backend5
      - backend6

  backend1:
    image: lab/backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - PORT=3001
    ports:
      - "3001:3001"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 25M

  backend2:
    image: lab/backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - PORT=3002
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 25M

  backend3:
    image: lab/backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - PORT=3003
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 25M

  backend4:
    image: lab/backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - PORT=3004
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 25M

  backend5:
    image: lab/backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - PORT=3006
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 25M

  backend6:
    image: lab/backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - PORT=3006
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 25M

