services:
  frontend:
   image: lab/frontend
   build:
     context: ./frontend
     dockerfile: Dockerfile
   environment:
     - PORT=3000
   ports:
     - "8080:5000"

  loadbalancer:
    image: nginx:1.27.4-alpine3.21
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "3000:3000"

  backend:
    image: lab/backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - PORT=3000
    ports:
      - "3000:3000"
